name: Ditto Text Updater
on: workflow_dispatch
jobs:
  UpdateDittoText:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Ditto text
        uses: dittowords/ditto-github-action@ash/dit-1724-github-action-allow-user-to-specify-root
        with:
          ditto-api-key: ${{ secrets.DITTO_API_KEY }}
          root-dir: "./tes"
