name: Ditto Text Updater
on: workflow_dispatch
jobs:
  UpdateDittoText:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Ditto text
        uses: dittowords/ditto-github-action@main
        with:
          ditto-api-key: ${{ secrets.DITTO_API_KEY }}
